template: |
  ## What’s Changed

  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
  
  ## SHA256 checksums
  ```
  
  ```

  ## Attention!
  We distribute our software only through https://github.com/pocketnetteam
  Any other resources offering to download executables, "installers" or source code are not related to the Pocketnet Team community

  ## Help
  https://github.com/pocketnetteam/pocketnet.core/issues
