name: Add new tasks to project

[![Add new tasks to project](https://github.com/pocketnetteam/pocketnet.core/actions/workflows/add.tasks.to.project.yml/badge.svg)](https://github.com/pocketnetteam/pocketnet.core/actions/workflows/add.tasks.to.project.yml)

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add new task to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/pocketnetteam/projects/3
          github-token: ${{ secrets.AUTO_PROJECT_TOKEN }}
          # labeled: bug, needs-triage
          # label-operator: OR or AND
