name: make check

on:
  workflow_dispatch:
  pull_request:
    branches: [ $default-branch, 0.20, 0.21 ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt-get update
    - name: install libdb
      run: sudo apt-get install libdb-dev libdb++-dev
    - name: install boost
      run: sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev
    - name: Install dependencies
      run: sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3 
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --with-incompatible-bdb --enable-tests
    - name: make
      run: make -j2
    - name: make check
      run: make check
    - name: make deploy
      run: make deploy
    - uses: actions/upload-artifact@v2
      with:
        name: package
        path: pocketnet*.deb