name: Build & Deploy Release Draft

on:
  workflow_dispatch:
  push:
    tags: v*.*.*

permissions:
  contents: read

jobs:

  BuildUnix:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Apt Update
        run: |
          sudo apt update
          sudo apt install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3 libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev

      - name: Download dependencies archive
        run: curl -O https://dev.pocketnet.app/x86_64-pc-linux-gnu.bz2
      - name: Unpack dependencies archive
        run: tar xjf x86_64-pc-linux-gnu.bz2

      - name: Prepare source code
        run: ./autogen.sh

      - name: Configure
        run: CONFIG_SITE=$PWD/x86_64-pc-linux-gnu/share/config.site ./configure --prefix=/usr/local

      - name: Make
        run: make -j8
      - name: Make Installer
        run: make deploy

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: unix
          path: |
            ./pocketnetcore_*
            ./release

  BuildWin:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Apt Update
        run: |
          sudo apt update
          sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils g++-mingw-w64-x86-64
          sudo update-alternatives --install /usr/bin/x86_64-w64-mingw32-g++ x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix 90



      - name: Download dependencies archive
        run: curl -O https://dev.pocketnet.app/x86_64-w64-mingw32.bz2
      - name: Unpack dependencies archive
        run: tar xjf x86_64-w64-mingw32.bz2

      - name: Prepare source code
        run: ./autogen.sh

      - name: Configure
        run: CONFIG_SITE=$PWD/x86_64-w64-mingw32/share/config.site ./configure CPPFLAGS='-D_MSC_VER_CROSS' --prefix=/

      - name: Make
        run: make -j8
      - name: Make Installer
        run: make deploy

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: win
          path: |
            ./pocketnetcore_*
            ./release


  TestsUnix:
    needs: BuildUnix
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Implement!"


  # TestsWin:
  #   needs: BuildWin


  # ReleaseDraft:
  #   needs: build
  #   permissions:
  #     contents: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: release-drafter/release-drafter@v5
  #       with:
  #         prerelease: true
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.release_token }}
