name: Release Draft

on:
  push:
    tags: v*.*.*

permissions:
  contents: read

jobs:

  CreateReleaseDraft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.release_token }}
